
@REM "C:\Program Files\Java\jdk1.8.0_271\bin\java.exe" -Dmaven.multiModuleProjectDirectory=D:\R_STUDIO\PRG\java\java-ee-projects\home-library-spr -Dmaven.home=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3 -Dclassworlds.conf=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\bin\m2.conf -Dmaven.ext.class.path=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven-event-listener.jar -javaagent:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\lib\idea_rt.jar=63473:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\bin -Dfile.encoding=UTF-8 -classpath C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\boot\plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2021.3.1 compile


@rem ========= Maven Build project =============
"C:\Program Files\Java\jdk1.8.0_271\bin\java.exe"^
 -Dmaven.multiModuleProjectDirectory=D:\R_STUDIO\PRG\java\java-ee-projects\home-library-spr^
 -Dmaven.home=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3^
 -Dclassworlds.conf=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\bin\m2.conf^
 -Dmaven.ext.class.path=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven-event-listener.jar^
 -javaagent:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\lib\idea_rt.jar=63473:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\bin^
 -Dfile.encoding=UTF-8^
 -classpath C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar^
;C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\boot\plexus-classworlds.license^
 org.codehaus.classworlds.Launcher^
 -Didea.version=2021.3.1^
 compile


@rem clean
@rem "C:\Program Files\Java\jdk1.8.0_271\bin\java.exe" -Dmaven.multiModuleProjectDirectory=D:\R_STUDIO\PRG\java\java-ee-projects\home-library-spr -Dmaven.home=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3 -Dclassworlds.conf=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\bin\m2.conf -Dmaven.ext.class.path=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven-event-listener.jar -javaagent:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\lib\idea_rt.jar=63490:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\bin -Dfile.encoding=UTF-8 -classpath C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\boot\plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2021.3.1 clean

@rem test
@rem "C:\Program Files\Java\jdk1.8.0_271\bin\java.exe" -Dmaven.multiModuleProjectDirectory=D:\R_STUDIO\PRG\java\java-ee-projects\home-library-spr -Dmaven.home=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3 -Dclassworlds.conf=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\bin\m2.conf -Dmaven.ext.class.path=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven-event-listener.jar -javaagent:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\lib\idea_rt.jar=63503:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\bin -Dfile.encoding=UTF-8 -classpath C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\boot\plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2021.3.1 test

@rem install
@rem "C:\Program Files\Java\jdk1.8.0_271\bin\java.exe" -Dmaven.multiModuleProjectDirectory=D:\R_STUDIO\PRG\java\java-ee-projects\home-library-spr -Dmaven.home=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3 -Dclassworlds.conf=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\bin\m2.conf -Dmaven.ext.class.path=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven-event-listener.jar -javaagent:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\lib\idea_rt.jar=63506:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\bin -Dfile.encoding=UTF-8 -classpath C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6461.79\plugins\maven\lib\maven3\boot\plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2021.3.1 install
